# Generated by Django 2.2.1 on 2019-08-26 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0003_auto_20190825_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sess_app.Department'),
            preserve_default=False,
        ),
    ]
