# Generated by Django 2.2.1 on 2019-08-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0004_auto_20190826_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cs_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='dep_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
