# Generated by Django 2.2.1 on 2019-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0006_auto_20190828_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
