# Generated by Django 2.2.1 on 2019-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0008_auto_20190828_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profiles',
            field=models.ManyToManyField(through='sess_app.UserCourse', to='sess_app.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(through='sess_app.UserCourse', to='sess_app.Course'),
        ),
    ]
