# Generated by Django 2.2.1 on 2019-08-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0009_auto_20190828_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
