# Generated by Django 2.2.1 on 2019-09-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0011_message_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdate',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
