# Generated by Django 2.2.1 on 2019-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0012_auto_20190902_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=1000000000000000, null=True),
        ),
    ]
