# Generated by Django 2.2.1 on 2019-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0014_auto_20190907_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp', models.CharField(max_length=100000)),
                ('tos', models.CharField(max_length=100000)),
            ],
        ),
    ]
