# Generated by Django 2.2.1 on 2019-09-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess_app', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='+989379852503', max_length=20),
            preserve_default=False,
        ),
    ]
